"""
A set of common vocabularies used in MIDAS queries.

"""

UK_COUNTIES = """ABERDEENSHIRE,ALDERNEY,ANGUS,ANTRIM,ARGYLL (IN HIGHLAND REGION),
ARGYLL (IN STRATHCLYDE REGION),ARGYLLSHIRE,ARMAGH,ASCENSION IS,
AUSTRALIA (ADDITIONAL ISLANDS),AVON,AYRSHIRE,BANFFSHIRE,BEDFORDSHIRE,
BERKSHIRE,BERWICKSHIRE,BORDERS,BOUVET ISLAND,BRECKNOCKSHIRE,BRITISH VIRGIN ISLANDS,
BUCKINGHAMSHIRE,BUTESHIRE,CAERNARFONSHIRE,CAITHNESS,CAMBRIDGESHIRE,CARDIGANSHIRE,
CARLOW,CARMARTHENSHIRE,CAVAN,CAYMAN ISLANDS,CENTRAL,CHANNEL ISLANDS,CHESHIRE,
CHRISTMAS ISLAND,CLACKMANNANSHIRE,CLARE,CLEVELAND,CLWYD,COCOS ISLAND,COOK ISLANDS,
CORK,CORNWALL,CUMBERLAND,CUMBRIA,CYPRUS,DENBIGHSHIRE,DERBYSHIRE,DETACHED ISLANDS,
DEVON,DONEGAL,DORSET,DOWN,DUBLIN,DUMFRIES & GALLOWAY,DUMFRIESSHIRE,DUNBARTONSHIRE,
DURHAM,DYFED,EAST LOTHIAN,EAST SUSSEX,ESSEX,FALKLAND IS,FERMANAGH,FIFE,FLINTSHIRE,
FORFARSHIRE,GALWAY,GLAMORGANSHIRE,GLOUCESTERSHIRE,GRAMPIAN,GREATER LONDON,
GREATER MANCHESTER,GUADALOUPE,GUERNSEY,GWENT,GWYNEDD,HAMPSHIRE,HAWAII,HEREFORD,
HEREFORD & WORCESTER,HERTFORDSHIRE,HIGHLAND,HUMBERSIDE,HUNTINGDONSHIRE,INVERNESS-SHIRE,
ISLE OF ANGLESEY,ISLE OF MAN,ISLE OF WIGHT,ISLES OF SCILLY,JERSEY,KENT,KERRY,KILDARE,
KILKENNY,KINCARDINESHIRE,KINROSS-SHIRE,KIRKCUDBRIGHTSHIRE,LANARKSHIRE,LANARKSHIRE,
LANCASHIRE,LAOIS,LEICESTERSHIRE,LEITRIM,LIMERICK,LINCOLNSHIRE,LONDONDERRY,LONGFORD,
LOTHIAN,LOUTH,MALDIVES,MALTA,MAYO,MEATH,MEDITERRANEAN ISLANDS,MERIONETHSHIRE,
MERSEYSIDE,MIDDLESEX,MID GLAMORGAN,MIDLOTHIAN,MIDLOTHIAN (IN BORDERS REGION),
MIDLOTHIAN (IN LOTHIAN REGION),MONAGHAN,MONMOUTHSHIRE,MONTGOMERYSHIRE,MORAY,
MORAY (IN GRAMPIAN REGION),MORAY (IN HIGHLAND REGION),NAIRNSHIRE,NORFOLK,
NORTHAMPTONSHIRE,NORTHUMBERLAND,NORTH YORKSHIRE,NOTTINGHAMSHIRE,OCEAN ISLANDS,
OFFALY,ORKNEY,OXFORDSHIRE,PACIFIC ISLANDS NORTH OF EQUATOR,PEEBLESHIRE,PEMBROKESHIRE,
PERTHSHIRE,PERTHSHIRE (IN CENTRAL REGION),PERTHSHIRE (IN TAYSIDE REGION),
PHOENIX ISLANDS,POWYS,POWYS (NORTH),POWYS (SOUTH),RADNORSHIRE,RENFREWSHIRE,ROSCOMMON,
ROSS & CROMARTY,ROXBURGHSHIRE,RUTLAND,SANTA CRUZ ISLANDS,SARK,SELKIRKSHIRE,SEYCHELLES,
SHETLAND,SHROPSHIRE,SINGAPORE,SLIGO,SOLOMON ISLANDS,SOMERSET,SOUTHERN LINE ISLANDS,
SOUTH GEORGIA,SOUTH GLAMORGAN,SOUTH ORKNEYS,SOUTH SHETLAND,SOUTH YORKSHIRE,
SPAIN (CANARY ISLANDS),STAFFORDSHIRE,ST HELENA,STIRLING,STIRLING (IN CENTRAL REGION),
STIRLING (IN STRATHCLYDE REGION),STRATHCLYDE,SUFFOLK,SURREY,SUSSEX,SUTHERLAND,TAYSIDE,
TIPPERARY,TURKS & CAICOS ISLANDS,TYNE & WEAR,TYRONE,WARWICKSHIRE,WATERFORD,WESTERN ISLES,
WEST GLAMORGAN,WEST LOTHIAN,WEST LOTHIAN (IN CENTRAL REGION),
WEST LOTHIAN (IN LOTHIAN REGION),WESTMEATH,WEST MIDLANDS,WESTMORLAND,WEST SUFFOLK,
WEST SUSSEX,WEST YORKSHIRE,WEXFORD,WICKLOW,WIGTOWNSHIRE,WILTSHIRE,WORCESTERSHIRE,
YORKSHIRE""".replace('\n', '').split(',')

DATA_TYPES = ['CLBD', 'CLBN', 'CLBR', 'CLBW', 'DCNN', 'FIXD', 'ICAO', 'LPMS', 'RAIN', 
'SHIP', 'WIND', 'WMO']

TABLE_NAMES = ['TD', 'WD', 'RD', 'RH', 'RS', 'ST', 'WH', 'WM', 'RO']

MIDAS_CATALOGUE_DICT = {
    "WM":   "http://catalogue.ceda.ac.uk/uuid/a1f65a362c26c9fa667d98c431a1ad38",
    "RH":   "http://catalogue.ceda.ac.uk/uuid/bbd6916225e7475514e17fdbf11141c1",
    "CURS": "http://catalogue.ceda.ac.uk/uuid/7f76ab4a47ee107778e0a7e8a701ee77",
    "ST":   "http://catalogue.ceda.ac.uk/uuid/8dc05f6ecc6065a5d10fc7b8829589ec",
    "GL":   "http://catalogue.ceda.ac.uk/uuid/0ec59f09b3158829a059fe70b17de951",
    "CUNS": "http://catalogue.ceda.ac.uk/uuid/bef3d059255a0feaa14eb78c77d7bc48",
    "TMSL": "http://catalogue.ceda.ac.uk/uuid/33ca1887e5f116057340e404b2c752f2",
    "RO":   "http://catalogue.ceda.ac.uk/uuid/b4c028814a666a651f52f2b37a97c7c7",
    "MO":   "http://catalogue.ceda.ac.uk/uuid/77910bcec71c820d4c92f40d3ed3f249",
    "RS":   "http://catalogue.ceda.ac.uk/uuid/455f0dd48613dada7bfb0ccfcb7a7d41",
    "RD":   "http://catalogue.ceda.ac.uk/uuid/c732716511d3442f05cdeccbe99b8f90",
    "CUNL": "http://catalogue.ceda.ac.uk/uuid/ec1d8e1e511838b9303921986a0137de",
    "TD":   "http://catalogue.ceda.ac.uk/uuid/1bb479d3b1e38c339adb9c82c15579d8",
    "SCLE": "http://catalogue.ceda.ac.uk/uuid/1d9aa0abc4e93fca1f91c8a187d46567",
    "WD":   "http://catalogue.ceda.ac.uk/uuid/954d743d1c07d1dd034c131935db54e0",
    "WH":   "http://catalogue.ceda.ac.uk/uuid/916ac4bbc46f7685ae9a5e10451bae7c",
    "CURL": "http://catalogue.ceda.ac.uk/uuid/fe9a02b85b50d3ee1d0b7366355bb9d8"
}
